language: node_js
sudo: required
node_js:
  - 7.9.0

# 指定缓存模块，可加快编译速度
cache:
  directories:
    - node_modules

# 指定博客源码分支，这里填入博客源码的分支名
branches:
  only:
    - hexo

before_install:
  - export TZ='Asia/Shanghai' # 更改时区

# S: Build Lifecycle
install:
  - npm install
  - npm install -g hexo-cli
  - npm install hexo-deployer-git --save

before_script:
 # - npm install -g gulp

script:
  - hexo clean
  - hexo generate

# 设置 git push 别名，邮箱。替换真实 token 到 _config.yml 文件中，然后 deploy 部署
after_script:
  - git config user.name "zenchen3331"
  - git config user.email "zenchen3331@gmail.com"
  - git clone https://github.com/zenchen3331/zenchen3331.github.io.git .deploy_git # 解决 commit 清空问题
  - cd .deploy_git
  - git checkout master
  - cd ../
  # 替换同目录下的_config.yml文件中gh_token字符串为travis后台刚才配置的变量，注意此处sed命令用了双引号。单引号无效！
  - sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml # 这里的 GH_TOKEN 名字要和网页中定义的别名一致
  - cat ./_config.yml
  - hexo deploy
# E: Build LifeCycle
## 如果以后要集成搜索可以参考 https://github.com/Felon03/Felon03.github.io/blob/source/.travis.yml



# ======================这种会清空commit，因为没有复制以前的提交。==========================
# language: node_js
#
# node_js: stable  # 要安装的node版本为当前的稳定版
#
# cache:
#   apt: true
#   directories:
#   - node_modules # 要缓存的文件夹
#
# install:
#   - npm install hexo-cli -g
#   - npm install # 安装hexo及插件
#
# script:
#   - hexo clean # 清除
#   - hexo g # 生成
#
# after_script:   # 最后执行的命令
#   - cd ./public
#   - git init
#   - git config user.name "zenchen3331"
#   - git config user.email "zenchen3331@gmail.com"
#   - git add .
#   - git commit -m "Travis CI Auto Builder"
#   - git push --force --quiet "https://${GITHUB_REPO_TOKEN}@${GH_REF}" master:master
#
# branches:
#   only:
#     - hexo # 触发持续集成的分支 # 只监测hexo分支
#
# env:
#  global:
#    - GH_REF: github.com/zenchen3331/zenchen3331.github.io.git
# - GH_REF: github.com/yourname/yourname.github.io.git #设置GH_REF，注意更改yourname


# ================历史配置，未成功，执拗的希望使用加密私钥的方式。===============
# language: node_js
#
# sudo: false
#
# node_js:
#   - '8'
#
# branches:
#   only:
#   - hexo
#
# # cache:
# #   directories:
# #     - node_modules
#
# before_install:
# # 这里是以前的，失效了，重新做了一个加密文件。
# # - openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv
# #   -in .travis/id_rsa.enc -out id_rsa -d
#
# # 这里的 github_deploy_key.enc 使用命令 travis encrypt-file github_deploy_key 来生成，然后把出现的下面一行复制到这里，注意路径。 .travis/github_deploy_key.enc 就是相对路径
# - openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv -in .travis/github_deploy_key.enc -out ~/.ssh/github_deploy_key -d
# - chmod 600 ~/.ssh/github_deploy_key
# - eval $(ssh-agent)
# - ssh-add ~/.ssh/github_deploy_key
# - cp .travis/ssh_config ~/.ssh/config
# - git config --global user.name 'zenchen3331'
# - git config --global user.email 'zenchen3331@gmail.com'
#
# install:
# - npm install hexo-cli -g
# - npm install
#
# script:
# - npm run deploy
# deploy:
#   provider: pages
#   skip-cleanup: true
#   # github-token: $GH_TOKEN
#   keep-history: true
#   on:
#     branch: master
#   local-dir: public


# ==================参考代码===================
# language: node_js
# node_js: stable
#
# # S: Build Lifecycle
# install:
#   - npm install
#
#
# #before_script:
#  # - npm install -g gulp
#
# script:
#   - hexo g
#
# after_script:
#   - cd ./public
#   - git init
#   - git config user.name "zzzlchen"
#   - git config user.email "zzzlchen3331@gmail.com"
#   - git add .
#   - git commit -m "Update docs"
#   - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# # E: Build LifeCycle
#
# branches:
#   only:
#     - blog-source
# env:
#  global:
#    - GH_REF: github.com/lifengsofts/lifengsofts.github.io.git
