language: node_js

sudo: false

node_js:
  - '8'

branches:
  only:
  - hexo

# cache:
#   directories:
#     - node_modules

before_install:
- openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv
  -in id_rsa.enc -out id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name 'zzzl'
- git config --global user.email zzzlchen@gmail.com

install:
- npm install hexo-cli -g
- npm install

script:
- npm run deploy

# language: node_js
# node_js: stable
#
# # S: Build Lifecycle
# install:
#   - npm install
#
#
# #before_script:
#  # - npm install -g gulp
#
# script:
#   - hexo g
#
# after_script:
#   - cd ./public
#   - git init
#   - git config user.name "zzzlchen"
#   - git config user.email "zzzlchen3331@gmail.com"
#   - git add .
#   - git commit -m "Update docs"
#   - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# # E: Build LifeCycle
#
# branches:
#   only:
#     - blog-source
# env:
#  global:
#    - GH_REF: github.com/lifengsofts/lifengsofts.github.io.git
